### PR TITLE
Fix Developer Guide

### LINKED ISSUE #193: [PE-D][Tester E] The term AB-3 is still being used in DG
the term `AB-3` is still used as the title in the Developer Guide.

Example:

￼

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: tanwartushar/ped#1

### PR DESCRIPTION
**Pull request by juancarlovieri**
Closes #193, #195, #198, #248, #255, #259, #262

### CODE REVIEW

**Comment by izruff** [comment]
Also closes #273

**Comment by izruff** [comment]
Fixes #253, #236, #221, and partially #280

**Comment by izruff** [comment]
Fixes #239

**Review by dominopizzaaaa — APPROVED** [review]
lgtm

**Pull request merged**
